import { z } from 'zod';
declare const envSchema: z.ZodObject<{
    TELEGRAM_BOT_TOKEN: z.ZodString;
    WEBHOOK_SECRET: z.ZodString;
    OPENROUTER_API_KEY: z.ZodOptional<z.ZodString>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    ANTHROPIC_API_KEY: z.ZodOptional<z.ZodString>;
    POLYGON_API_KEY: z.ZodOptional<z.ZodString>;
    ALPHAVANTAGE_API_KEY: z.ZodOptional<z.ZodString>;
    BINANCE_KEY: z.ZodOptional<z.ZodString>;
    BINANCE_SECRET: z.ZodOptional<z.ZodString>;
    BYBIT_KEY: z.ZodOptional<z.ZodString>;
    BYBIT_SECRET: z.ZodOptional<z.ZodString>;
    DATABASE_URL: z.ZodString;
    REDIS_URL: z.ZodString;
    PORT: z.ZodEffects<z.ZodNumber, number, unknown>;
    NODE_ENV: z.ZodEnum<["development", "production", "test"]>;
    LOG_LEVEL: z.ZodEnum<["info", "warn", "error", "debug", "verbose"]>;
    DEFAULT_RISK_PCT: z.ZodEffects<z.ZodNumber, number, unknown>;
    MAX_LEVERAGE: z.ZodEffects<z.ZodNumber, number, unknown>;
    MIN_RR: z.ZodEffects<z.ZodNumber, number, unknown>;
    DATA_STALENESS_SEC: z.ZodEffects<z.ZodNumber, number, unknown>;
    BACKTEST_MAX_YEARS: z.ZodEffects<z.ZodNumber, number, unknown>;
    SCAN_TOP_K: z.ZodEffects<z.ZodOptional<z.ZodNumber>, number | undefined, unknown>;
    SCAN_DEFAULT_MARKETS: z.ZodOptional<z.ZodString>;
    UNIVERSE_CRYPTO: z.ZodOptional<z.ZodString>;
    UNIVERSE_SPX: z.ZodOptional<z.ZodString>;
    UNIVERSE_BIST: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    TELEGRAM_BOT_TOKEN: string;
    WEBHOOK_SECRET: string;
    DATABASE_URL: string;
    REDIS_URL: string;
    PORT: number;
    NODE_ENV: "development" | "production" | "test";
    LOG_LEVEL: "error" | "warn" | "info" | "debug" | "verbose";
    DEFAULT_RISK_PCT: number;
    MAX_LEVERAGE: number;
    MIN_RR: number;
    DATA_STALENESS_SEC: number;
    BACKTEST_MAX_YEARS: number;
    OPENROUTER_API_KEY?: string | undefined;
    OPENAI_API_KEY?: string | undefined;
    ANTHROPIC_API_KEY?: string | undefined;
    POLYGON_API_KEY?: string | undefined;
    ALPHAVANTAGE_API_KEY?: string | undefined;
    BINANCE_KEY?: string | undefined;
    BINANCE_SECRET?: string | undefined;
    BYBIT_KEY?: string | undefined;
    BYBIT_SECRET?: string | undefined;
    SCAN_TOP_K?: number | undefined;
    SCAN_DEFAULT_MARKETS?: string | undefined;
    UNIVERSE_CRYPTO?: string | undefined;
    UNIVERSE_SPX?: string | undefined;
    UNIVERSE_BIST?: string | undefined;
}, {
    TELEGRAM_BOT_TOKEN: string;
    WEBHOOK_SECRET: string;
    DATABASE_URL: string;
    REDIS_URL: string;
    NODE_ENV: "development" | "production" | "test";
    LOG_LEVEL: "error" | "warn" | "info" | "debug" | "verbose";
    OPENROUTER_API_KEY?: string | undefined;
    OPENAI_API_KEY?: string | undefined;
    ANTHROPIC_API_KEY?: string | undefined;
    POLYGON_API_KEY?: string | undefined;
    ALPHAVANTAGE_API_KEY?: string | undefined;
    BINANCE_KEY?: string | undefined;
    BINANCE_SECRET?: string | undefined;
    BYBIT_KEY?: string | undefined;
    BYBIT_SECRET?: string | undefined;
    PORT?: unknown;
    DEFAULT_RISK_PCT?: unknown;
    MAX_LEVERAGE?: unknown;
    MIN_RR?: unknown;
    DATA_STALENESS_SEC?: unknown;
    BACKTEST_MAX_YEARS?: unknown;
    SCAN_TOP_K?: unknown;
    SCAN_DEFAULT_MARKETS?: string | undefined;
    UNIVERSE_CRYPTO?: string | undefined;
    UNIVERSE_SPX?: string | undefined;
    UNIVERSE_BIST?: string | undefined;
}>;
export type Env = z.infer<typeof envSchema>;
export declare const env: {
    TELEGRAM_BOT_TOKEN: string;
    WEBHOOK_SECRET: string;
    DATABASE_URL: string;
    REDIS_URL: string;
    PORT: number;
    NODE_ENV: "development" | "production" | "test";
    LOG_LEVEL: "error" | "warn" | "info" | "debug" | "verbose";
    DEFAULT_RISK_PCT: number;
    MAX_LEVERAGE: number;
    MIN_RR: number;
    DATA_STALENESS_SEC: number;
    BACKTEST_MAX_YEARS: number;
    OPENROUTER_API_KEY?: string | undefined;
    OPENAI_API_KEY?: string | undefined;
    ANTHROPIC_API_KEY?: string | undefined;
    POLYGON_API_KEY?: string | undefined;
    ALPHAVANTAGE_API_KEY?: string | undefined;
    BINANCE_KEY?: string | undefined;
    BINANCE_SECRET?: string | undefined;
    BYBIT_KEY?: string | undefined;
    BYBIT_SECRET?: string | undefined;
    SCAN_TOP_K?: number | undefined;
    SCAN_DEFAULT_MARKETS?: string | undefined;
    UNIVERSE_CRYPTO?: string | undefined;
    UNIVERSE_SPX?: string | undefined;
    UNIVERSE_BIST?: string | undefined;
};
export {};
